# Generated by Django 5.2 on 2025-05-04 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0002_activitylog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ActivityLog',
        ),
    ]
