name: Django + Postgres CI

on:
  push:
    branches:
      - master
      - rbac

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:17
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: admin
          POSTGRES_DB: mapdata
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./TowerMap/requirements.txt
      
      - name: Set Firebase credentials and save to file
        env:
          FIREBASE_CREDENTIALS: ${{ secrets.FIREBASE_CREDENTIALS }}
        run: |
          mkdir -p ./TowerMap/Firebase
          echo "${FIREBASE_CREDENTIALS}" > ./TowerMap/Firebase/towermap-b98ee-firebase-adminsdk-fbsvc-d502a34283.json
          echo "Firebase credentials saved to ./TowerMap/Firebase/towermap-b98ee-firebase-adminsdk-fbsvc-d502a34283.json"

      - name: Set Firebase environment variables
        env:
          FIREBASE_CREDENTIALS_PATH: Firebase/towermap-b98ee-firebase-adminsdk-fbsvc-d502a34283.json
          FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
          FIREBASE_AUTH_DOMAIN: ${{ secrets.FIREBASE_AUTH_DOMAIN }}
          FIREBASE_DATABASE_URL: ${{ secrets.FIREBASE_DATABASE_URL }}
          FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
          FIREBASE_STORAGE_BUCKET: ${{ secrets.FIREBASE_STORAGE_BUCKET }}
          FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}
          FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
        run: |
          echo "Firebase secrets are set!"

      - name: Run Django migrations
        env:
          FIREBASE_CREDENTIALS_PATH: Firebase/towermap-b98ee-firebase-adminsdk-fbsvc-d502a34283.json
          FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
          FIREBASE_AUTH_DOMAIN: ${{ secrets.FIREBASE_AUTH_DOMAIN }}
          FIREBASE_DATABASE_URL: ${{ secrets.FIREBASE_DATABASE_URL }}
          FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
          FIREBASE_STORAGE_BUCKET: ${{ secrets.FIREBASE_STORAGE_BUCKET }}
          FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}
          FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
          DATABASE_NAME: mapdata
          DATABASE_USER: postgres
          DATABASE_PASSWORD: admin
          DATABASE_HOST: localhost
          DATABASE_PORT: 5432
        run: |
          cd ./TowerMap/
          python manage.py makemigrations
          python manage.py migrate

      - name: Load SQL data into Postgres
        env:
          PGPASSWORD: admin
        run: |
          psql -U postgres -h localhost -p 5432 -d mapdata -f dummy_towers.sql

      - name: Run tests
        run: |
          cd ./TowerMap/
          python manage.py runserver
