name: Django + Postgres CI

on:
  push:
    branches:
      - master
      - rbac

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:17
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: admin
          POSTGRES_DB: mapdata
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Django migrations
        env:
          DATABASE_NAME: mapdata
          DATABASE_USER: postgres
          DATABASE_PASSWORD: admin
          DATABASE_HOST: localhost
          DATABASE_PORT: 5432
        run: |
          python manage.py migrate

      - name: Load SQL data into Postgres
        env:
          PGPASSWORD: admin
        run: |
          psql -U postgres -h localhost -p 5432 -d mapdata -f dummy_towers.sql

      - name: Run tests
        run: |
          python manage.py runserver
